### ISSUE TITLE
Post-deploy produces confusing error

### ISSUE THREAD

**Issue by akranga** [epam/hubctl#48]
Steps to reproduce:

1. Define a component in the `hub.yaml` as follows

```yaml
components
- name: dex
  source:
    dir: components/dex
    git:
      remote: https://github.com/epam/kubeflow-components.git
      subDir: dex
  hooks:
  - file: bin/dex-post-deploy.sh
    triggers: [post-deploy]
```

2. Run `hubctl stack deploy:` 

> Note: post-deploy hook not exists!

4. See logs

```text
2023/06/09 00:56:56 Error: exec: no command
2023/06/09 00:56:56 One of post-deploy hooks failed. See logs
2023/06/09 00:56:56 Wrote state `/Users/akranga/kubeflow/semantic-search-infra/app-runtime/.hub/
```

Actual results:

1. There are no logs
2. Error message is misleading

Expected results:

1. Hubctl should not deploy proceed with the deployment if hooks not found. And fail with explicit error message

Rationale: Such deployment won't be successful in any case. Then the deployment should not be started
